server:
  port: 8080

templates:
  vm:
    id: "vm-template-1"
    name: "Basic VM Template"
    file: "templates/vm-template.tmpl"
  kubernetes:
    id: "k8s-template-1"
    name: "Basic Kubernetes Template"
    file: "templates/kubernetes-template.tmpl"