apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount.server }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-server
          image: "{{ .Values.image.server.repository }}:{{ .Values.image.server.tag }}"
          imagePullPolicy: {{ .Values.image.server.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.server | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: templates-volume
              mountPath: /app/templates
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
        - name: templates-volume
          configMap:
            name: {{ .Release.Name }}-templates